version: "2"

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    volumes:
      - ${MINIO_VOLUME}:/data
    command: server /data
  app:
    build: flask
    image: ccmbio/st2020
    environment:
      FLASK_ENV: production
      ST_DATABASE_URI: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}"
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    command: prod --bind 0.0.0.0:5000 --preload --workers 1 --threads 2
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes:
      - ./react/build:/var/www/sample-tracker/react/build
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
#     - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
      - minio
    command: nginx -g "daemon off;"
