version: "2"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    volumes:
      - ${MINIO_VOLUME}:/data
    command: server /data
  app:
    build: flask
    image: ccmbio/st2020
    environment:
      FLASK_ENV: development
      ST_DATABASE_URI: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}"
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - minio
    volumes:
      - ./flask:/var/www/sample-tracker/flask
