version: "3.8"

services:
  mysql:
    image: mysql:8.0
    user: "${MYSQL_UIDGID:-mysql}"
    environment:
      MYSQL_DATABASE: "${TEST_MYSQL_DATABASE}"
      MYSQL_USER: "${TEST_MYSQL_USER}"
      MYSQL_PASSWORD: "${TEST_MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${TEST_MYSQL_ROOT_PASSWORD}"
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: "${TEST_MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${TEST_MINIO_SECRET_KEY}"
    command: server /data
  app:
    build: flask
    image: ghcr.io/ccmbioinfo/stager:dev
    user: "${FLASK_UIDGID:-www-data}"
    environment:
      FLASK_ENV: development
      TEST_ST_DATABASE_URI: "mysql+pymysql://${TEST_MYSQL_USER}:${TEST_MYSQL_PASSWORD}@mysql/${TEST_MYSQL_DATABASE}"
      TEST_MINIO_ENDPOINT: minio:9000
      TEST_MINIO_ACCESS_KEY: "${TEST_MINIO_ACCESS_KEY}"
      TEST_MINIO_SECRET_KEY: "${TEST_MINIO_SECRET_KEY}"
    depends_on:
      - mysql
      - minio
    volumes:
      - ./flask:/usr/src/stager
    command: pytest
