version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
  minio:
    image: minio/minio
    restart: on-failure
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    ports:
      - "${MINIO_HOST_PORT}:9000"
    volumes:
      - ${MINIO_VOLUME}:/data
    command: server /data
  app:
    build: flask
    image: ghcr.io/ccmbioinfo/stager:dev
    environment:
      FLASK_ENV: development
      ST_DATABASE_URI: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}"
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    ports:
      - "${FLASK_HOST_PORT}:5000"
    depends_on:
      - mysql
      - minio
    volumes:
      - ./flask:/usr/src/stager
