name: Compile and lint frontend
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/react.yml
      - react/**/*
  pull_request:
    branches:
      - '*'
    paths:
      - .github/workflows/react.yml
      - react/**/*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - REACT_APP_MINIO_URL: https://sampletrackerdev.ccm.sickkids.ca/minio/
            MC_HOST_minio: ${{ secrets.MINIO_CCM_DEV }}
            MINIO_BUCKET: ${{ secrets.MINIO_CCM_DEV_BUCKET }}
            if: true
          - REACT_APP_MINIO_URL: https://minio.genomics4rd.ca/
            MC_HOST_minio: ${{ secrets.MINIO_CHEO_RI_DEV }}
            MINIO_BUCKET: ${{ secrets.MINIO_CHEO_RI_BUCKET }}
            if: ${{ github.event_name == 'push' }}
    defaults:
      if: ${{ matrix.if }}
      run:
        working-directory: react
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Get yarn cache path
      id: yarn-cache-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: restore
      with:
        path: |
          ${{ steps.yarn-cache-path.outputs.dir }}
          react/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install
      if: steps.restore.outputs.cache-hit != 'true'
    - run: yarn build
      env:
        REACT_APP_NAME: Stager
        REACT_APP_MINIO_URL: ${{ matrix.REACT_APP_MINIO_URL }}
    - run: yarn lint
    - run: yarn check-format
    # - run: yarn test -- --coverage
    - name: Deploy to MinIO bucket
      if: github.event_name == 'push'
      env:
        MC_HOST_minio: ${{ matrix.MC_HOST_minio }}
      run: |
        sudo curl --output /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
        sudo chmod +x /usr/local/bin/mc
        ./deploy.sh minio ${{ matrix.MINIO_BUCKET }}
